export const posts = [
    {
        id:1,
        title: 'Title 1',
        img: "https://images.pexels.com/photos/12241512/pexels-photo-12241512.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolore similique corporis blanditiis, totam vero molestiae dolorem quasi possimus explicabo.",
        descLong: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Delectus sequi deleniti itaque voluptate quia ad. Est, nemo. Voluptate accusamus possimus, odit, consectetur totam, voluptas modi unde ipsum ipsam non necessitatibus sint. Itaque, autem veritatis? Soluta magnam reiciendis laborum. Velit, molestias nesciunt. A non alias aliquam error amet accusantium officiis neque in culpa, pariatur dignissimos consectetur hic blanditiis quasi ipsa voluptate fugiat aut enim quia beatae minima magnam sunt tenetur omnis. Natus libero obcaecati minima tenetur quo, nisi porro quidem odio expedita. Necessitatibus voluptatem deleniti illo nisi, sunt minima culpa numquam officiis laudantium nulla eos molestiae ab quis ea vero velit eaque sapiente cumque nostrum, eligendi possimus cupiditate dolor? Accusamus consectetur numquam voluptatum voluptates unde harum iusto, fugit dolorum voluptatibus ipsam ipsa nesciunt. Eligendi illo in, excepturi itaque magnam pariatur eius iure non id cupiditate, officia omnis nisi deserunt, labore expedita vitae eos ullam dolorum mollitia perspiciatis dolore sed! Quod amet dolorem possimus perspiciatis asperiores. Dolorum, facilis quia non repudiandae veniam corporis nobis doloremque vitae quod numquam soluta odit expedita animi fuga iusto voluptatibus perferendis magni perspiciatis exercitationem officia ad, unde sapiente neque! Excepturi sequi quam necessitatibus repellendus facere odio atque libero eos error, qui, amet, fuga eligendi. Eum, placeat. Accusantium temporibus maxime sapiente molestias, qui nam provident quas. Id nulla fuga culpa eligendi quidem asperiores? Nihil nesciunt, dolor maxime doloribus, quod laborum autem velit omnis debitis quibusdam consectetur repudiandae fugiat excepturi? Aperiam, sequi enim! Cumque odio obcaecati nulla a unde in aperiam, optio possimus ex. Veritatis corporis impedit ipsam fuga!"
    },
    {
        id:2,
        title: 'TItle 2',
        img: "https://images.pexels.com/photos/11491782/pexels-photo-11491782.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolore similique corporis blanditiis, totam vero molestiae dolorem quasi possimus explicabo.",
        descLong: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Delectus sequi deleniti itaque voluptate quia ad. Est, nemo. Voluptate accusamus possimus, odit, consectetur totam, voluptas modi unde ipsum ipsam non necessitatibus sint. Itaque, autem veritatis? Soluta magnam reiciendis laborum. Velit, molestias nesciunt. A non alias aliquam error amet accusantium officiis neque in culpa, pariatur dignissimos consectetur hic blanditiis quasi ipsa voluptate fugiat aut enim quia beatae minima magnam sunt tenetur omnis. Natus libero obcaecati minima tenetur quo, nisi porro quidem odio expedita. Necessitatibus voluptatem deleniti illo nisi, sunt minima culpa numquam officiis laudantium nulla eos molestiae ab quis ea vero velit eaque sapiente cumque nostrum, eligendi possimus cupiditate dolor? Accusamus consectetur numquam voluptatum voluptates unde harum iusto, fugit dolorum voluptatibus ipsam ipsa nesciunt. Eligendi illo in, excepturi itaque magnam pariatur eius iure non id cupiditate, officia omnis nisi deserunt, labore expedita vitae eos ullam dolorum mollitia perspiciatis dolore sed! Quod amet dolorem possimus perspiciatis asperiores. Dolorum, facilis quia non repudiandae veniam corporis nobis doloremque vitae quod numquam soluta odit expedita animi fuga iusto voluptatibus perferendis magni perspiciatis exercitationem officia ad, unde sapiente neque! Excepturi sequi quam necessitatibus repellendus facere odio atque libero eos error, qui, amet, fuga eligendi. Eum, placeat. Accusantium temporibus maxime sapiente molestias, qui nam provident quas. Id nulla fuga culpa eligendi quidem asperiores? Nihil nesciunt, dolor maxime doloribus, quod laborum autem velit omnis debitis quibusdam consectetur repudiandae fugiat excepturi? Aperiam, sequi enim! Cumque odio obcaecati nulla a unde in aperiam, optio possimus ex. Veritatis corporis impedit ipsam fuga!"
    },
    {
        id:3,
        title: 'TItle 3',
        img: "https://images.pexels.com/photos/11635798/pexels-photo-11635798.jpeg",
        desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolore similique corporis blanditiis, totam vero molestiae dolorem quasi possimus explicabo.",
        descLong: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Delectus sequi deleniti itaque voluptate quia ad. Est, nemo. Voluptate accusamus possimus, odit, consectetur totam, voluptas modi unde ipsum ipsam non necessitatibus sint. Itaque, autem veritatis? Soluta magnam reiciendis laborum. Velit, molestias nesciunt. A non alias aliquam error amet accusantium officiis neque in culpa, pariatur dignissimos consectetur hic blanditiis quasi ipsa voluptate fugiat aut enim quia beatae minima magnam sunt tenetur omnis. Natus libero obcaecati minima tenetur quo, nisi porro quidem odio expedita. Necessitatibus voluptatem deleniti illo nisi, sunt minima culpa numquam officiis laudantium nulla eos molestiae ab quis ea vero velit eaque sapiente cumque nostrum, eligendi possimus cupiditate dolor? Accusamus consectetur numquam voluptatum voluptates unde harum iusto, fugit dolorum voluptatibus ipsam ipsa nesciunt. Eligendi illo in, excepturi itaque magnam pariatur eius iure non id cupiditate, officia omnis nisi deserunt, labore expedita vitae eos ullam dolorum mollitia perspiciatis dolore sed! Quod amet dolorem possimus perspiciatis asperiores. Dolorum, facilis quia non repudiandae veniam corporis nobis doloremque vitae quod numquam soluta odit expedita animi fuga iusto voluptatibus perferendis magni perspiciatis exercitationem officia ad, unde sapiente neque! Excepturi sequi quam necessitatibus repellendus facere odio atque libero eos error, qui, amet, fuga eligendi. Eum, placeat. Accusantium temporibus maxime sapiente molestias, qui nam provident quas. Id nulla fuga culpa eligendi quidem asperiores? Nihil nesciunt, dolor maxime doloribus, quod laborum autem velit omnis debitis quibusdam consectetur repudiandae fugiat excepturi? Aperiam, sequi enim! Cumque odio obcaecati nulla a unde in aperiam, optio possimus ex. Veritatis corporis impedit ipsam fuga!"
    }
]
